import { jsx, jsxs } from "react/jsx-runtime";
import { useCallback, useEffect, useMemo } from "react";
import { getCurrentWindow } from "../adapters/tauri";
import "../App.css";
import openaiLogo from "../assets/openai.svg";
import opencodeLogo from "../assets/opencode.svg";
import vscodeLogo from "../assets/vscode.svg";
import {
  MCP_CONFIG_PLACEHOLDER,
  MCP_PRESET_OPTIONS,
  SUPPORTED_EDITORS,
} from "../constants";
import {
  dashboardCurrentByMode,
  formatCurrentErrorWithProfile,
} from "../utils";
import { SortableProfileCard, McpIcon, SkillTargetSwitch } from "./components";
import { renderDashboardHeader, renderDashboardMain } from "./dashboardViews";
import { renderToolViews } from "./toolViews";
import {
  renderBlockingOverlay,
  renderClosePromptDialog,
  renderSettingsDialog,
  renderStatusBar,
} from "./overlayViews";
import { useRuntimeStateBootstrap } from "./stateBootstrap";
import { useAppRuntimeControllerEffects } from "./hooks/useAppRuntimeControllerEffects";
import { useDashboardSync } from "./hooks/useDashboardSync";
import { useDashboardCommandHandlers } from "./hooks/useDashboardCommandHandlers";
import { useRuntimeDerivedViewState } from "./hooks/useRuntimeDerivedViewState";
import { useToolsPanelLogic } from "./hooks/useToolsPanelLogic";
import { useRuntimeLifecyclePolling } from "./hooks/useRuntimeLifecyclePolling";
import { useRuntimeStatusActions } from "./hooks/useRuntimeStatusActions";
function App() {
  const {
    activeAppMode,
    activeAppModeRef,
    activeProfileByMode,
    activeProfileByModeRef,
    activeToolView,
    autoEnabledRef,
    autoHookUpgradeRunningRef,
    autoKeepalive,
    autoRefreshOnStartup,
    autoRunningRef,
    autoSeamlessSwitch,
    autoTimerRef,
    blockingMessage,
    blockingRef,
    busy,
    busyRef,
    bypassCloseInterceptRef,
    closePromptOpen,
    closePromptRemember,
    codexExtInfo,
    currentErrorCandidateRef,
    currentErrorCandidateSinceRef,
    dashboard,
    dashboardRef,
    dashboardSignatureRef,
    displayCurrentErrorText,
    displayProfiles,
    hookInstalled,
    hookListenerVsCodeLastPollAtRef,
    hookListenerWarnedRef,
    hookVersionSnapshot,
    importBackupInputRef,
    initialLoading,
    liveStatusErrorStreakRef,
    liveStatusErrorTimesRef,
    liveStatusNextFetchAtRef,
    liveStatusPollingRef,
    mcpBusyIds,
    mcpFormClaudeEnabled,
    mcpFormCodexEnabled,
    mcpFormConfig,
    mcpFormDescription,
    mcpFormDocs,
    mcpFormError,
    mcpFormGeminiEnabled,
    mcpFormHomepage,
    mcpFormId,
    mcpFormName,
    mcpFormOpencodeEnabled,
    mcpFormTags,
    mcpManage,
    mcpManageError,
    mcpManageLoading,
    mcpManageRefreshing,
    mcpSelectedPreset,
    mcpShowMetadata,
    opencodeMonitorStatus,
    pendingSortNamesRef,
    postSwitchStrategy,
    quotaQuerying,
    refreshingProfileNames,
    seamlessEnabledRef,
    seamlessRunningRef,
    seamlessTimerRef,
    selected,
    setActiveAppMode,
    setActiveProfileByMode,
    setActiveToolView,
    setAutoKeepalive,
    setAutoRefreshOnStartup,
    setAutoSeamlessSwitch,
    setBlockingMessage,
    setBusy,
    setClosePromptOpen,
    setClosePromptRemember,
    setCodexExtInfo,
    setDashboard,
    setDisplayCurrentErrorText,
    setDisplayProfiles,
    setHookInstalled,
    setHookVersionSnapshot,
    setInitialLoading,
    setMcpBusyIds,
    setMcpFormClaudeEnabled,
    setMcpFormCodexEnabled,
    setMcpFormConfig,
    setMcpFormDescription,
    setMcpFormDocs,
    setMcpFormError,
    setMcpFormGeminiEnabled,
    setMcpFormHomepage,
    setMcpFormId,
    setMcpFormName,
    setMcpFormOpencodeEnabled,
    setMcpFormTags,
    setMcpManage,
    setMcpManageError,
    setMcpManageLoading,
    setMcpManageRefreshing,
    setMcpSelectedPreset,
    setMcpShowMetadata,
    setOpenCodeMonitorStatus,
    setPostSwitchStrategy,
    setQuotaQuerying,
    setRefreshingProfileNames,
    setSelected,
    setSettingsEditorTarget,
    setSettingsOpen,
    setSkillRepoActionBusyKeys,
    setSkillRepoBranch,
    setSkillRepoInput,
    setSkillReposManage,
    setSkillReposManageError,
    setSkillReposManageLoading,
    setSkillReposManageRefreshing,
    setSkillsBusyIds,
    setSkillsCatalog,
    setSkillsDiscovery,
    setSkillsDiscoveryError,
    setSkillsDiscoveryInstallFilter,
    setSkillsDiscoveryInstallingIds,
    setSkillsDiscoveryKeyword,
    setSkillsDiscoveryLoading,
    setSkillsDiscoveryRefreshing,
    setSkillsError,
    setSkillsLoading,
    setSkillsRefreshing,
    setStatusText,
    setVsCodeStatus,
    setWindowCloseAction,
    settingsEditorTarget,
    settingsOpen,
    skillRepoActionBusyKeys,
    skillRepoBranch,
    skillRepoInput,
    skillReposManage,
    skillReposManageError,
    skillReposManageLoading,
    skillReposManageRefreshing,
    skillsBusyIds,
    skillsCatalog,
    skillsDiscovery,
    skillsDiscoveryError,
    skillsDiscoveryInstallFilter,
    skillsDiscoveryInstallingIds,
    skillsDiscoveryKeyword,
    skillsDiscoveryLoading,
    skillsDiscoveryRefreshing,
    skillsError,
    skillsLoading,
    skillsRefreshing,
    sortSavingRef,
    startupKeepaliveCheckedRef,
    startupQuotaRefreshDoneRef,
    statusText,
    threadRecoverRunningRef,
    threadRecoverTimerRef,
    vscodeStatus,
    windowCloseAction,
  } = useRuntimeStateBootstrap();
  const switchAppMode = useCallback((mode) => {
    setActiveAppMode(mode);
    setStatusText(`\u5DF2\u5207\u6362\u5230 ${mode === "gpt" ? "GPT" : "OpenCode"} \u6A21\u5F0F`);
  }, [setActiveAppMode, setStatusText]);
  const minimizeWindowToBackground = useCallback(async () => {
    try {
      const window2 = getCurrentWindow();
      await window2.hide();
      setStatusText("\u7A97\u53E3\u5DF2\u9690\u85CF\u5230\u7CFB\u7EDF\u6258\u76D8\u3002");
    } catch (err) {
      setStatusText(`\u5207\u5230\u7CFB\u7EDF\u6258\u76D8\u5931\u8D25: ${String(err)}`);
    }
  }, [setStatusText]);
  const exitApplicationWindow = useCallback(async () => {
    bypassCloseInterceptRef.current = true;
    try {
      await getCurrentWindow().close();
    } catch (err) {
      bypassCloseInterceptRef.current = false;
      setStatusText(`\u5173\u95ED\u7A97\u53E3\u5931\u8D25: ${String(err)}`);
    }
  }, [bypassCloseInterceptRef, setStatusText]);
  const handleClosePromptAction = useCallback(
    async (action) => {
      const remember = closePromptRemember;
      setClosePromptOpen(false);
      setClosePromptRemember(false);
      if (remember) {
        setWindowCloseAction(action);
      }
      if (action === "exit") {
        await exitApplicationWindow();
      } else {
        await minimizeWindowToBackground();
      }
    },
    [closePromptRemember, exitApplicationWindow, minimizeWindowToBackground, setClosePromptOpen, setClosePromptRemember, setWindowCloseAction]
  );
  const {
    applyMcpPreset,
    closeMcpAddPage,
    filteredDiscoverySkills,
    loadMcpManage,
    loadSkillReposManage,
    loadSkillsCatalog,
    loadSkillsDiscovery,
    mcpSummaryText,
    mcpSyncingEmpty,
    onAddSkillRepo,
    onDeleteSkill,
    onFormatMcpConfig,
    onImportExistingMcp,
    onInstallDiscoverySkill,
    onOpenDiscoverSkillReadme,
    onOpenMcpDoc,
    onOpenRepoHome,
    onOpenSkillReposManage,
    onRefreshMcpManage,
    onRefreshSkillsCatalog,
    onRemoveMcpServer,
    onRemoveSkillRepo,
    onSkillsDiscover,
    onSkillsImportExisting,
    onSkillsInstallFromZip,
    onSubmitMcpAdd,
    onToggleMcpTarget,
    onToggleSkillTarget,
    openMcpAddPage,
    skillReposSyncingEmpty,
    skillsDiscoverySummaryText,
    skillsDiscoverySyncingEmpty,
    skillsSummaryText,
  } = useToolsPanelLogic({
    activeToolView,
    mcpFormConfig,
    mcpFormId,
    mcpFormClaudeEnabled,
    mcpFormCodexEnabled,
    mcpFormGeminiEnabled,
    mcpFormOpencodeEnabled,
    skillRepoBranch,
    skillRepoInput,
    skillsCatalog,
    skillsDiscovery,
    skillsDiscoveryInstallFilter,
    skillsDiscoveryKeyword,
    skillsLoading,
    skillsRefreshing,
    skillsDiscoveryLoading,
    skillsDiscoveryRefreshing,
    skillReposManage,
    skillReposManageLoading,
    skillReposManageRefreshing,
    mcpManage,
    mcpManageLoading,
    mcpManageRefreshing,
    setActiveToolView,
    setMcpBusyIds,
    setMcpFormClaudeEnabled,
    setMcpFormCodexEnabled,
    setMcpFormConfig,
    setMcpFormDescription,
    setMcpFormDocs,
    setMcpFormError,
    setMcpFormGeminiEnabled,
    setMcpFormHomepage,
    setMcpFormId,
    setMcpFormName,
    setMcpFormOpencodeEnabled,
    setMcpFormTags,
    setMcpManage,
    setMcpManageError,
    setMcpManageLoading,
    setMcpManageRefreshing,
    setMcpSelectedPreset,
    setMcpShowMetadata,
    setSkillRepoActionBusyKeys,
    setSkillRepoInput,
    setSkillReposManage,
    setSkillReposManageError,
    setSkillReposManageLoading,
    setSkillReposManageRefreshing,
    setSkillsBusyIds,
    setSkillsCatalog,
    setSkillsDiscovery,
    setSkillsDiscoveryError,
    setSkillsDiscoveryInstallingIds,
    setSkillsDiscoveryLoading,
    setSkillsDiscoveryRefreshing,
    setSkillsError,
    setSkillsLoading,
    setSkillsRefreshing,
    setStatusText,
  });
  const { applyDashboard, loadDashboard, refreshCurrentDashboardSilent } = useDashboardSync({
    activeAppModeRef,
    blockingRef,
    busyRef,
    dashboardRef,
    dashboardSignatureRef,
    liveStatusErrorStreakRef,
    liveStatusErrorTimesRef,
    liveStatusNextFetchAtRef,
    liveStatusPollingRef,
    setBusy,
    setDashboard,
    setDisplayProfiles,
    setInitialLoading,
    setSelected,
    setStatusText,
  });
  const {
    currentLine,
    currentProfileName,
    filteredProfiles,
    hookListenerBadge,
    liveQueryProfileName,
    liveQuotaMergeTargetName,
    modeActiveProfileName,
    modeCurrent,
    opencodeListenerBadge,
    profileLabel,
    rawCurrentErrorText,
    refreshingProfileNameSet,
    selectedProfile,
  } = useRuntimeDerivedViewState({
    activeAppMode,
    activeProfileByMode,
    dashboard,
    displayProfiles,
    hookInstalled,
    initialLoading,
    opencodeMonitorStatus,
    refreshingProfileNames,
    selected,
    setSelected,
    vscodeStatus,
  });
  const uiBusy = busy && !initialLoading;
  const settingsTargetName = settingsEditorTarget === "kiro" ? "Kiro Codex" : "VSCode Codex";
  const settingsTargetShortName = settingsEditorTarget === "kiro" ? "Kiro" : "VSCode";
  const {
    onAddByLogin,
    onApplySelected,
    onDeleteSelected,
    onDragEnd,
    onExportDataBackup,
    onImportDataBackupClick,
    onImportDataBackupFileSelected,
    onRefreshAllQuota,
    onRefreshSelectedQuota,
    onRefreshStartupQuota,
    onSetAlias,
    profileIds,
    sensors,
  } = useDashboardCommandHandlers({
    activeAppMode,
    activeAppModeRef,
    activeProfileByModeRef,
    applyDashboard,
    currentProfileName,
    dashboard,
    displayProfiles,
    filteredProfiles,
    importBackupInputRef,
    loadDashboard,
    modeActiveProfileName,
    pendingSortNamesRef,
    profileLabel,
    selectedProfile,
    setActiveProfileByMode,
    setBlockingMessage,
    setBusy,
    setDisplayProfiles,
    setQuotaQuerying,
    setRefreshingProfileNames,
    setStatusText,
    sortSavingRef,
    uiBusy,
  });
  useEffect(() => {
    if (initialLoading || startupQuotaRefreshDoneRef.current) {
      return;
    }
    startupQuotaRefreshDoneRef.current = true;
    if (autoRefreshOnStartup) {
      void onRefreshStartupQuota();
    }
  }, [autoRefreshOnStartup, initialLoading, onRefreshStartupQuota, startupQuotaRefreshDoneRef]);
  const {
    onInjectHookOneClick,
    onInstallCodexHook,
    onReloadVsCode,
    onRunPostSwitchStrategy,
    refreshCodexExtensionInfo,
    refreshHookStatus,
    refreshOpenCodeMonitorStatus,
    refreshVsCodeStatus,
    runPostSwitchStrategy,
  } = useRuntimeStatusActions({
    postSwitchStrategy,
    settingsEditorTarget,
    settingsTargetName,
    settingsTargetShortName,
    setBusy,
    setCodexExtInfo,
    setHookInstalled,
    setHookVersionSnapshot,
    setOpenCodeMonitorStatus,
    setPostSwitchStrategy,
    setStatusText,
    setVsCodeStatus,
    vscodeStatus,
  });
  useAppRuntimeControllerEffects({
    activeAppMode,
    activeAppModeRef,
    activeProfileByMode,
    activeProfileByModeRef,
    blockingMessage,
    blockingRef,
    busy,
    busyRef,
    bypassCloseInterceptRef,
    currentErrorCandidateRef,
    currentErrorCandidateSinceRef,
    exitApplicationWindow,
    initialLoading,
    loadDashboard,
    minimizeWindowToBackground,
    modeActiveProfileName,
    rawCurrentErrorText,
    refreshCodexExtensionInfo,
    refreshCurrentDashboardSilent,
    refreshVsCodeStatus,
    setActiveProfileByMode,
    setClosePromptOpen,
    setClosePromptRemember,
    setDisplayCurrentErrorText,
    settingsOpen,
    windowCloseAction,
  });
  useRuntimeLifecyclePolling({
    activeAppMode,
    applyDashboard,
    autoEnabledRef,
    autoHookUpgradeRunningRef,
    autoKeepalive,
    autoRefreshOnStartup,
    autoRunningRef,
    autoSeamlessSwitch,
    autoTimerRef,
    blockingRef,
    busyRef,
    dashboardRef,
    hookInstalled,
    hookListenerVsCodeLastPollAtRef,
    hookListenerWarnedRef,
    hookVersionSnapshot,
    initialLoading,
    postSwitchStrategy,
    refreshCodexExtensionInfo,
    refreshHookStatus,
    refreshOpenCodeMonitorStatus,
    refreshVsCodeStatus,
    runPostSwitchStrategy,
    seamlessEnabledRef,
    seamlessRunningRef,
    seamlessTimerRef,
    setActiveProfileByMode,
    setAutoSeamlessSwitch,
    setBusy,
    setHookVersionSnapshot,
    setSelected,
    setStatusText,
    startupKeepaliveCheckedRef,
    threadRecoverRunningRef,
    threadRecoverTimerRef,
    vscodeStatus,
    windowCloseAction,
  });
  return /* @__PURE__ */ jsxs("div", { className: "app-root", children: [
    /* @__PURE__ */ jsx(
      "input",
      {
        ref: importBackupInputRef,
        type: "file",
        accept: ".tar,.tar.gz,.tgz,application/x-tar,application/gzip",
        style: { display: "none" },
        onChange: onImportDataBackupFileSelected
      }
    ),
    renderBlockingOverlay({ blockingMessage }),
    renderClosePromptDialog({ closePromptOpen, closePromptRemember, handleClosePromptAction, setClosePromptOpen, setClosePromptRemember }),
    renderSettingsDialog({ codexExtInfo, hookInstalled, hookVersionSnapshot, onExportDataBackup, onImportDataBackupClick, onInjectHookOneClick, onInstallCodexHook, onRunPostSwitchStrategy, postSwitchStrategy, refreshHookStatus, refreshVsCodeStatus, settingsEditorTarget, settingsOpen, settingsTargetName, settingsTargetShortName, setPostSwitchStrategy, setSettingsEditorTarget, setSettingsOpen, setWindowCloseAction, SUPPORTED_EDITORS, uiBusy, vscodeStatus, windowCloseAction }),
    renderDashboardHeader({
      activeAppMode,
      activeToolView,
      autoKeepalive,
      autoRefreshOnStartup,
      autoSeamlessSwitch,
      onAddByLogin,
      onRefreshAllQuota,
      onReloadVsCode,
      quotaQuerying,
      setActiveToolView,
      setAutoKeepalive,
      setAutoRefreshOnStartup,
      setAutoSeamlessSwitch,
      setSettingsOpen,
      switchAppMode,
      uiBusy,
      vscodeStatus,
      McpIcon,
      openaiLogo,
      opencodeLogo,
      vscodeLogo,
    }),
    renderDashboardMain({
      activeAppMode,
      activeToolView,
      currentLine,
      dashboard,
      displayCurrentErrorText,
      filteredProfiles,
      initialLoading,
      liveQueryProfileName,
      liveQuotaMergeTargetName,
      modeActiveProfileName,
      modeCurrent,
      onApplySelected,
      onDeleteSelected,
      onDragEnd,
      onRefreshSelectedQuota,
      onSetAlias,
      profileIds,
      quotaQuerying,
      refreshingProfileNameSet,
      selected,
      sensors,
      setSelected,
      SortableProfileCard,
      uiBusy,
    }),
    renderToolViews({
      activeToolView,
      applyMcpPreset,
      closeMcpAddPage,
      loadSkillReposManage,
      loadSkillsDiscovery,
      mcpBusyIds,
      mcpFormClaudeEnabled,
      mcpFormCodexEnabled,
      mcpFormConfig,
      mcpFormDescription,
      mcpFormDocs,
      mcpFormError,
      mcpFormGeminiEnabled,
      mcpFormHomepage,
      mcpFormId,
      mcpFormName,
      mcpFormOpencodeEnabled,
      mcpFormTags,
      mcpManage,
      mcpManageError,
      mcpManageLoading,
      mcpManageRefreshing,
      mcpSelectedPreset,
      mcpShowMetadata,
      mcpSummaryText,
      mcpSyncingEmpty,
      MCP_CONFIG_PLACEHOLDER,
      MCP_PRESET_OPTIONS,
      onAddSkillRepo,
      onDeleteSkill,
      onFormatMcpConfig,
      onImportExistingMcp,
      onInstallDiscoverySkill,
      onOpenDiscoverSkillReadme,
      onOpenMcpDoc,
      onOpenRepoHome,
      onOpenSkillReposManage,
      onRefreshMcpManage,
      onRefreshSkillsCatalog,
      onRemoveMcpServer,
      onRemoveSkillRepo,
      onSkillsDiscover,
      onSkillsImportExisting,
      onSkillsInstallFromZip,
      onSubmitMcpAdd,
      onToggleMcpTarget,
      onToggleSkillTarget,
      openMcpAddPage,
      openaiLogo,
      opencodeLogo,
      setActiveToolView,
      setMcpFormClaudeEnabled,
      setMcpFormCodexEnabled,
      setMcpFormConfig,
      setMcpFormDescription,
      setMcpFormDocs,
      setMcpFormGeminiEnabled,
      setMcpFormHomepage,
      setMcpFormId,
      setMcpFormName,
      setMcpFormOpencodeEnabled,
      setMcpFormTags,
      setMcpShowMetadata,
      setSkillRepoBranch,
      setSkillRepoInput,
      setSkillsDiscoveryInstallFilter,
      setSkillsDiscoveryKeyword,
      setStatusText,
      skillRepoActionBusyKeys,
      skillRepoBranch,
      skillRepoInput,
      skillReposManage,
      skillReposManageError,
      skillReposManageLoading,
      skillReposManageRefreshing,
      skillReposSyncingEmpty,
      skillsBusyIds,
      skillsCatalog,
      skillsDiscovery,
      skillsDiscoveryError,
      skillsDiscoveryInstallFilter,
      skillsDiscoveryInstallingIds,
      skillsDiscoveryKeyword,
      skillsDiscoveryLoading,
      skillsDiscoveryRefreshing,
      skillsDiscoverySummaryText,
      skillsDiscoverySyncingEmpty,
      skillsError,
      skillsLoading,
      skillsRefreshing,
      skillsSummaryText,
      SkillTargetSwitch,
      filteredDiscoverySkills,
    }),
    renderStatusBar({ hookListenerBadge, opencodeListenerBadge, quotaQuerying, statusText, uiBusy })
  ] });
}
var App_default = App;
export {
  App_default as default
};
